### ISSUE TITLE
AWTRIX on ESP32 D1 mini - Data-Pin? / matrix type?

### ISSUE THREAD

**Issue by parabacus** [Blueforcer/awtrix-light#782]
I'm having some initial problems building my awtrix3.

I successfully flashed awtrix onto an ESP32 D1 mini using https://blueforcer.github.io/awtrix3/#/flasher?id=awtrix-20-controller-upgrade-with-esp32-d1-mini and was able to integrate it into my home network via the web interface and access it. So far, everything is working.
I encountered my first problems when connecting the 8x32 matrix. I connected GPIO32 to the matrix's Data-In pin, as shown in the table, but nothing was displayed.
I then checked all the pins with an oscilloscope and determined that the problem must be with the GPIO21 signal line, as I could see a signal pattern that changed every few seconds, as is also visible in LiveView.

After connecting the matrix to GPIO21, it did display something, but only garbled pixel patterns.
Unfortunately, the attempt to change the matrix type was unsuccessful - regardless of which type 0, 1 or 2 I tried.

The LED matrix is ​​an 8x32 WS2812B RGB:
https://de.aliexpress.com/item/4001296811800.html?spm=a2g0o.order_list.order_list_main.53.169d1802yIBMJp&gatewayAdapt=glo2deu

The ESP32 D1 mini is this one:
https://de.aliexpress.com/item/1005006059791568.html?spm=a2g0o.order_list.order_list_main.115.4e331802fjgEdv&gatewayAdapt=glo2deu

Nothing else is connected yet.

What am I doing wrong, or what do I need to do to get a correct display?
Do I have an incompatible ESP32 board or a matrix that doesn't fit?

**Comment by parabacus** [comment]
I solved it myself. ;-)

After a short break to think it over and review the documentation again, I realized I hadn't named the JSON file dev.json. Once I corrected that and set the matrix type to 2, everything is working as expected.

**Comment by obs945** [comment]
Hi @parabacus , I am in the same sitution with same hardwares.

Could you advice what you did to solve the issue ?

I wired data-in pin to GPIO 32.

**Comment by parabacus** [comment]
I used GPIO21 after locating the signal there, and it works perfectly.
GPIO21 is right next to GPIO32 (towards the inside).
I hope it works for you too.

**Comment by obs945** [comment]
Hi @parabacus !  I switched pinout from GPIO32 to GPIO21 and also indicated matrix type 2 in dev.json but LED matrix still not showing anything even a blink. Could you advice which power supply you use for the project ?  (I use 5V 2A power supply)

**Comment by parabacus** [comment]
Hi @obs945,

I'm currently using a lab power supply with a 5A max output. I assume the brightness is currently set to 100. Under normal operating conditions, my device needs just over 1A. However, it could need much more during startup, which is why I think your device is constantly restarting. Try using a more powerful power supply.
